---
title: "Capstone Project - Healthcare Associated Infections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(broom)
library(tidyverse)
library(shinycssloaders)
library(shiny)
library(RSQLite)
library(stringr)
library(ggmap)
library(ggplot2)
library(zipcode)
library(tidyverse)
library(scales)
library(leaflet)
library(DT)
library(plotly)
library(maps)
library(DBI)
```

```{r global}
#Data from https://catalog.data.gov/dataset/healthcare-associated-infections-hospital-3ca5e

# connect to the database and get the data
#con = dbConnect(RSQLite::SQLite(), dbname='HAI.sqlite')
#rs = dbSendQuery(con, "SELECT * FROM medicare")
#data = dbFetch(rs)
#dbDisconnect(con)

data <- read_csv(file.path('Healthcare_Associated_Infections.csv')) %>% 
  rename(ZIP.Code             = `ZIP Code`,
         Measure.Name         = `Measure Name`,
         Hospital.Name        = `Hospital Name`,
         Compared.to.National = `Compared to National`,
         Phone.Number         = `Phone Number`)


# clean the zip codes and set the lat/long for each
data$zip = clean.zipcodes(data$ZIP.Code)
data(zipcode)
data=inner_join(data,zipcode)
data$latlon = paste(data$latitude,data$longitude)

df = data %>%
  mutate( Measure.Split = Measure.Name ) %>%
  separate( Measure.Split, c("Infection","Metric"), extra='merge',
            fill='right' )
  # mutate(Infection = factor(Infection))
rm( data )


ALL_FILTER_NAME <- "All"
stateChoices       = c(ALL_FILTER_NAME, sort(unique(df$State)))
cityChoices        = c(ALL_FILTER_NAME, sort(unique(df$City)))
zipcodeChoices     = c(ALL_FILTER_NAME, sort(unique(df$ZIP.Code)))
hospitalChoices    = c(ALL_FILTER_NAME, sort(unique(df$Hospital.Name)))
measureNameChoices = factor(c(sort(unique(df$Measure.Name))))
infectionChoices   = factor(c(sort(unique(df$Infection))))
metricChoices      = factor(c(sort(unique(df$Metric))))

# Change types
df$Measure.Name <- as.factor(df$Measure.Name)
df$Measure       = as.factor(df$Infection)
df$Metric        = as.factor(df$Metric)
df$Score        <- as.numeric(df$Score)

# Slider properties
SLIDER_MIN_VALUE  <-   0
SLIDER_MAX_VALUE  <- 100
SLIDER_INIT_VALUE <-  25

# Datatable properties
MAX_ITEMS_PER_PAGE <- SLIDER_INIT_VALUE
TABLE_PAGING             <- TRUE
LENGTH_MENU              <- c(5, 10, 15, 20, 25, 50, 75, 100)
FORMAT_COLUMN            <- "Compared.to.National"
FORMAT_COLUMN_VALUE      <- "Better than the National Benchmark"
FORMAT_COLUMN_VALUE_WARN <- "Worse than the National Benchmark"
FORMAT_COLUMN_COLOR      <- "lightgreen"
FORMAT_COLUMN_COLOR_WARN <- "#ff6666"
```

```{r reg}
#df_disease = df %>%
   #filter(Infection == "MRSA")
#reg = lm(Score ~ State, data = df_disease)
#summary(reg)
```


```{r servercode}
# get data to update cities based on state
getStateData <- reactive({
  result <- df
  if ( input$stateFilter != ALL_FILTER_NAME ) {
    result <- result %>% filter(State == input$stateFilter)
  }
  return(result)
})
  
# get data to update metrics based on infection
getInfectionData <- reactive({
  return( df %>% filter(Infection == input$infectionFilter) )
})
  
# Get input data for ƒmeasurement for hospital versus score
getMeasureData <- reactive({
  data = df %>% filter( !is.na(Score) )

  # apply filters
  if ( input$stateFilter != ALL_FILTER_NAME ){
    data <- data %>% filter(State == input$stateFilter)
  }
  if ( input$cityFilter != ALL_FILTER_NAME ){
    data <- data %>% filter(City == input$cityFilter)
  }
  if (input$infectionFilter != ALL_FILTER_NAME){
    data <- data %>% filter(Infection == input$infectionFilter)
  }
  if (input$metricFilter != ALL_FILTER_NAME){
    data <- data %>% filter(Metric == input$metricFilter)
  }
  
  data <- data %>% arrange(-Score)

  return( data %>% head(input$maxResults )  )
})
getMeasureData_2 <- reactive({
  data = df %>% filter( !is.na(Score) )

  # apply filters
  if ( input$stateFilter != ALL_FILTER_NAME ){
    data <- data %>% filter(State == input$stateFilter)
  }
  if ( input$cityFilter != ALL_FILTER_NAME ){
    data <- data %>% filter(City == input$cityFilter)
  }
  if (input$infectionFilter != ALL_FILTER_NAME){
    data <- data %>% filter(Infection == input$infectionFilter)
  }
  if (input$metricFilter != ALL_FILTER_NAME){
    data <- data %>% filter(Metric == input$metricFilter)
  }
  
  data <- data %>% arrange(-Score)
  sample_size <- min(nrow(data),input$maxResults ) - 1
  
#  if (sample_size >= 4){ 
#    return( data %>% sample_n(sample_size,replace = TRUE) ) }
#  else {
#     return( data )
#  }
  
return( data )
  
})

getNationalData <- reactive({
  data = df %>% filter( !is.na(Score) ) %>% arrange(-Score)
    if (input$metricFilter != ALL_FILTER_NAME){
  data <- data %>% filter(Metric == input$metricFilter) 
  }
  data <- data %>% arrange(-Score)

  sample_size <- min(nrow(data),input$maxResults ) - 1
  
#  if (sample_size >= 4){ 
#    return( data %>% sample_n(sample_size, replace = TRUE) ) }
#  else {
#     return( data )
#  }
 return( data )

})





# interactive plot
output$chart = renderPlotly({
  df_filtered <- getMeasureData()
  req( nrow(df_filtered) > 0 )
    
  # change to factor otherwise plotly doesn't display it in right order
  df_filtered$Hospital.Name <- factor(
    df_filtered$Hospital.Name,
    levels = rev(df_filtered$Hospital.Name)
  )

  #margin and plot
  m <- list( l = 300, r = 0, b = 40, t = 40, pad = 4 )
  
  plot_ly(
    df_filtered,
    x = ~Score, y = ~Hospital.Name,
    type = "scatter",
    hoverinfo = 'text',
    text = ~paste('State: ', State, ";",
                  'City: ', City, ";", 
                  'Score: ', Score, ";")
  ) %>% layout(
    title = paste("Scores per hospital for measure:",
                  input$infectionFilter, input$metricFilter),
    xaxis = list(title = "Score"),
    yaxis = list(title = ""),
    margin = m
  ) %>% config(displayModeBar = F) 
})


output$dataTable = renderDataTable({
  df_filtered <- getMeasureData_2()
  
  result <- df_filtered %>% arrange(Measure.Name, -Score) %>% select(
    Measure.Name,          latlon,Hospital.Name,  Score,
    Compared.to.National,  State,                City,
    Address,               Phone.Number
  )
  
  
    
  # Hide some columns
  hideCols <- grep("latlon|Address|Phone.Number", colnames(result)) - 1
  
  datatable(
      result, 
      rownames = FALSE,
      extensions = 'Buttons', class = "compact",
      options = list(
        pageLength = MAX_ITEMS_PER_PAGE, 
        lengthMenu = LENGTH_MENU,
        paging = TABLE_PAGING,
        pagingType='simple',
        dom = 'Blfrtip',
        columnDefs = list(list(visible = FALSE, targets = hideCols)), # hide columns
        buttons = list(
          list(extend = 'csv', exportOptions = list(columns = ':visible')),
          list(extend = 'pdf', exportOptions = list(columns = ':visible')),
          list(extend = 'colvis', text='Show/Hide Columns', collectionLayout='fixed two-column')
        )
      )
    ) %>% formatStyle(
      FORMAT_COLUMN, target = 'row',
      backgroundColor = styleEqual(
        c(FORMAT_COLUMN_VALUE, FORMAT_COLUMN_VALUE_WARN),
        c(FORMAT_COLUMN_COLOR, FORMAT_COLUMN_COLOR_WARN)
      )
    )
  })
  
  # map with all locatiƒons 
  output$map <- renderLeaflet({
    df_filtered <- getMeasureData()
    df_filtered$ScoreRel <- sqrt(df_filtered$Score / max(df_filtered$Score, na.rm = TRUE))
    leaflet()  %>%
      setView(lng = df_filtered[1,]$longitude, lat = df_filtered[1,]$latitude, zoom = 6) %>%
      
      addProviderTiles("Stamen.Terrain", options = providerTileOptions(noWrap = TRUE)) %>% 
      addCircleMarkers(data = df_filtered, lat = ~latitude, lng = ~longitude, radius = ~ScoreRel*20, color = "#FF4742")
  })
  
  # Show a popup at the given location
  showPopup <- function(id, lat, lng) {
    df_filtered <- getMeasureData()
    row <- df_filtered[df_filtered$latitude == lat & df_filtered$longitude == lng,]
    content <- paste(
      "Hospital:", row$Hospital.Name, "<br>",
      "Score:", row$Score, "<br>")
    leafletProxy("map") %>% addPopups(lng, lat, content, layerId = id)
  }
  
  # When map is clicked, show a popup
  observeEvent(input$map_marker_click, {
    leafletProxy("map") %>% clearPopups()
    event <- input$map_marker_click
    if (is.null(event))
      return()
    
    isolate({
      showPopup(event$id, event$lat, event$lng)
    })
  })
  
  
  output$densityPlot <- renderPlotly({ 
    df_filtered <- getMeasureData_2()
    density1 <- density(df_filtered$Score)
    p <- plot_ly(
      x = ~ density1$x, 
      
      y = ~ density1$y,type='scatter', 
      mode = 'lines', fill='tozroy')
      p %>% layout (dragmode = 'select')
})

   output$dataSummarySelection <- renderTable({
    df_filtered <- getMeasureData_2()
    df_filtered %>% 
      group_by(State,City) %>% 
      summarize(mean = mean(Score)) %>% 
      ungroup
})
  
  output$dataSummaryAll <- renderTable({
    df_filtered <- getNationalData()
    df_filtered %>% 
      group_by(State,City) %>% 
      summarize(mean = mean(Score)) %>% 
      ungroup
})
 output$boxPlotData <- renderTable({
  
  df_filtered <- getMeasureData_2() %>% 
    mutate (selected = "Current") %>%  
    select(Hospital.Name, Score, selected)  
  
  df_all <- getNationalData() %>% 
    select(City, State, Hospital.Name, Metric, Score) %>% 
    mutate (selected = "All")  
  
  df_combined <- df_all  %>%  
    left_join (df_filtered, by = 'Hospital.Name')  %>% 
    mutate(Score = coalesce(Score.x,Score.y)) %>% 
    mutate(selected = coalesce(selected.y,selected.x)) %>% 
    mutate(label = 'Score') %>% 
    mutate (scoreLog = log(Score))
 
  
  df_combined %>%  
    group_by(selected,City,State) %>%  
    summarize(Score = mean(Score),
              scoreLog = mean(scoreLog)) %>%  
    ungroup
}) 
 
output$boxPlot <- renderPlotly({
  
    df_filtered <- getMeasureData_2() %>% 
    mutate (selected = "Current") %>%  
    select(Hospital.Name, Score, selected)  
  
  df_all <- getNationalData() %>% 
    select(City, State, Hospital.Name, Metric, Score) %>% 
    mutate (selected = "All")  
  
  df_combined <- df_all  %>%  
    left_join (df_filtered, by = 'Hospital.Name')  %>% 
    mutate(Score = coalesce(Score.x,Score.y)) %>% 
    mutate(selected = coalesce(selected.y,selected.x)) %>% 
    mutate(label = 'Score') %>% 
    mutate (Scorelog = log(Score))
 
  y <- list(title = 'Infection Score')
  x <- list(title = 'Selected Score')
  
  p <- plot_ly(y     = ~ df_combined$Scorelog, 
               color = ~ df_combined$selected, 
               type = 'box') %>% 
    layout(dragmode = 'select', xaxis = x, yaxis= y)
})
      
  
  # Update cities when selecting state
  observeEvent(input$stateFilter, {
    df_filtered <- getStateData()
    updateSelectInput(
      session, "cityFilter", label = "City:", 
      choices = append(ALL_FILTER_NAME, unique(df_filtered$City))
    )
  }, ignoreInit = TRUE)
  
  # Update metrics when selecting infection
  observeEvent(input$infectionFilter, {
    df_filtered <- getInfectionData()
    updateSelectInput(
      session, "metricFilter", label = "Metric:", 
      choices = unique(df_filtered$Metric)
    )
  }, ignoreInit = TRUE)
```

Column{.sidebar}
-----------------------------------------------------------------------
``` {r thesidebar}

helpText("Pick One:")

selectInput("stateFilter", 
            label = "State:",
            choices = stateChoices,
            selected = ALL_FILTER_NAME)

selectInput("cityFilter",
            label = 'City:',
            choices = cityChoices,
            selected = ALL_FILTER_NAME)

selectInput("infectionFilter",
            label = 'Infection:',
            choices = infectionChoices,
            selected = 'MRSA')

selectInput("metricFilter",
            label = 'Metric:',
            choices = metricChoices,
            selected = 'Predicted Cases')

sliderInput("maxResults", "Maximum results",
            min = SLIDER_MIN_VALUE,
            max = SLIDER_MAX_VALUE, 
            value = SLIDER_INIT_VALUE)
```

Output {.tabset}
-----------------------------------------------------------------------

### Measure per hospital plot

```{r}
plotlyOutput("chart",width='100%', height = '800px')
```

### Measure per hospital map

```{r}
leafletOutput("map", height = "800px")
```

### Measure per hospital data

```{r}
dataTableOutput("dataTable")
```

### Density

```{r}
plotlyOutput("densityPlot")
```

### Box Plot Data

```{r}
tableOutput("boxPlotData")
```

### Box Plot

```{r}
plotlyOutput("boxPlot")
```

### Data Selection

```{r}
tableOutput("dataSummarySelection")
```

### Summary All
```{r}
tableOutput("dataSummaryAll")
```

```{r}
#dataTableOutput("dataTable1")
#plotOutput("dataTable1")
#tableOutput("dataTable2")
#plotlyOutput("boxplot")
```
